_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batch_size:
    value: 108
checkpoint_dir:
    value: bt_model
epochs:
    value: 200
image_path:
    value: null
lr:
    value: 0.2
lr_bias:
    value: 0.0048
mask_ratio:
    value: 0.75
save_epoch:
    value: 50
seed:
    value: 42
weight_decay:
    value: 1.5e-06
